algorithm-study-2408/coding-tests-study-2412

src/hyojin/dfs/네트워크.java, src/hyojin/sort/호텔객실.java
- sort, dfs
- **레벨**: 2
- **문제명**: 호텔객실
- **문제 링크**: [호텔객실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
- **레벨**: 3
- **문제명**: 네트워크
- **문제 링크**: [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- 
- 겹치는 시간, 그래프 탐색 로직에 대해서 공부할 수 있었습니다.
- 네트워크는 처음에 dfs로 하는 건가?싶었지만 다르게 접근하다가 시간을 많이 잡아먹었고, 정답지를 보니까 dfs가 맞더라구요. 다시 복습할 수 있었습니다!
- 네트워크 문제에서 입출력에 예를 보고 바로 이해가 안 갔는데, 다들 어떻게 접근해서 파악하셨는지 궁금합니다.
=> 호텔객식, 네트워크 문제풀이

src/seyoung/HotelRoom.java, src/seyoung/Network.java, src/seyoung/Network_dfs.java
- dfs
- **레벨**: 2
- **문제명**: 호텔객실
- **문제 링크**: [호텔객실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
- **문제풀이**: [62b5bff](https://github.com/algorithm-study-2408/coding-tests-study-2412/pull/5/commits/62b5bffbc433edc8761a57ae8084e6a7a0c115e7)
- **레벨**: 3
- **문제명**: 네트워크
- **문제 링크**: [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- **문제풀이1 (오답)**: [f82c05f](https://github.com/algorithm-study-2408/coding-tests-study-2412/pull/5/commits/f82c05f57de8945b5f0e136e1173c1b719cfe4a1)
- 브릿지 문제인 걸 보는 순간 dfs를 떠올렸으나 아직 활용이 미숙함을 인정하고 다른 방식으로 풀어보려다 장렬히 실패
- **문제풀이2 (정답)**: [a23c92a](https://github.com/algorithm-study-2408/coding-tests-study-2412/pull/5/commits/a23c92a9c29dec83f2ccc31c823de06b8b54bf32)
- -> 위 실패 후 많은 삽질 후 정답 코드 참고하여 작성
- 누적합에 대해 좀 더 공부해 볼 것
- …
=> [홍세영] 1주차 실전문제풀이

src/yeonjae/dfs/네트워크.java, src/yeonjae/prefixsum/호텔객실.java, src/yeonjae/queue/다리를지나는트럭.java
- 큐
- **레벨**: 2
- **문제 링크**: [다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
- 처음에 문제를 이해하기가 좀 어려웠지만 손으로 그림그려가며 패턴을 파악하니 문제가 쉽게 풀렸습니다.
- 패턴은 찾았지만 구현하는데 좀 어려움이 있어서 이부분은 더 노력해야겠다고 깨달았습니다.
- 정확히 어떤 알고리즘 유형인지 잘 모르겠습니다.
=> [정연재] 2주차 월요일 일일문제풀이

.idea/git_toolbox_blame.xml, src/jonghun/week01/네트워크.java, src/jonghun/week01/호텔객실.java
- [prefix sum, dfs]
- **레벨**: 2
- **문제명**: 호텔대실
- **문제 링크**: [호텔객실](https://school.programmers.co.kr/learn/courses/30/lessons/155651)
- **레벨**: 3
- **문제명**: 네트워크
- **문제 링크**: [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- 누적합에 대한 공부. dfs에 대한 공부. (사실 둘다 답지 봄)
- 코테 경험도 없고 알고리즘과 자료구조가 하나도 기억이 안나서 몇년만에 다시 공부하려다 보니 많이 버겁네요..ㅠ 
- 최대한 열심히 따라가 보겠습니다... 코딩 자아성찰..
=> [주종훈] 1주차 실전문제풀이

src/jonghun/week02/다리를지나는트럭.java
- Queue
- **레벨**: 2
- **문제 링크**: [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
- 큐에 대해 다시 공부할 수 있었습니다.
- 현재 제 코드는 객체지향적이지 않은데, 객체지향적으로 푸는 방법에 익숙해져야 할 것 같습니다.
=> [주종훈] 2주차 월요일 일일문제풀이

src/seyoung/_2412_1주차/HotelRoom.java, src/seyoung/_2412_1주차/Network.java, src/seyoung/_2412_1주차/Network_dfs.java, src/seyoung/_2412_2주차/다리를_지나는_트럭.java
- 큐
- **레벨**: 2
- **문제 링크**: [다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
- **문제 풀이** : [6cc5b71](https://github.com/algorithm-study-2408/coding-tests-study-2412/pull/11/commits/6cc5b7198689f4c27281c9bef36d42a16d18a995)
- 큐의 활용... 오랜만에 코테 공부를 시작했더니 했던 것도 잘 안된다. 재활이 시급...
- 평소에 알고리즘과 자료구조에 대한 이론 정리는 어떻게 하시나요?
=> [홍세영] 2주차 월요일 일일 문제풀이

src/hyojin/queue/다리를지나는트럭.java
- 큐
- **레벨**: 2
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/42583
- 처음에는 트럭 객체만 선언하여 접근했지만, 비즈니스 로직을 구현하는 과정에서 고민이 생겼습니다.
- 다리를 지나는 동안 반복문을 어떻게 처리할지, 트럭에게 어떤 행위를 부여할지에 대한 어려움이 있었습니다.
- 힌트를 참고하여 추가 객체가 필요하다는 점을 알게 되었고, 다리라는 객체에서 로직을 처리할 수 있음을 깨달았습니다.
- 이렇게 하여 트럭 객체가 다리 위에서의 행위를 적절히 처리하도록 구조를 개선할 수 있었습니다. 
- 객체의 역할과 행위가 적절한가요?
=> [우효진] 2주차 월요일 일일문제풀이

src/jonghun/week02/양궁대회.java
- Backtracking
- **레벨**: 2
- **문제명**: 양국대회
- **문제 링크**: [양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)
- 백트래킹에 대해 공부해서 풀었는데 점점 익숙해지고 있는 것 같습니다
- 푸느라 시간이 꽤 오래 걸렸네요.. 그리고 테스트시간이 좀 오래 걸렸는데.. 더 좋은 다른 풀이 방법도 있을까요?
=> [주종훈] 2주차 화요일 일일 문제풀이

src/jaehoon/_02주차/Lv02_다리를지나는트럭.java, src/jaehoon/_02주차/Lv02_다리를지나는트럭_객체지향.java
- 큐
- **레벨**: 2
- **문제 링크**: [다리를 지나는 트럭](https://school.programmers.co.kr/learn/courses/30/lessons/42583)
- [배운 점 입력]
- 순서대로 처리할때는 큐를 이용하면 쉽게 풀 수 있다는 것
- 객체지향으로 푼 것도 있는데 변수명, 메서드명 짓느라 시간 소모 엄청되네요. 그냥 푸는게 좋을 것 같아요 ㅎㅎ
=> [이재훈] 2주차 월요일 일일문제풀이

src/yeonjae/dfs/양궁대회_backtracking.java, src/yeonjae/dfs/양궁대회_dfs.java, src/yeonjae/hash/베스트앨범.java
- dfs, backtracking
- 2
- 양궁대회
- **문제 링크**: [양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)
- 모든 경우의수를 탐색해야한다고 생각해서 dfs를 사용했었는데 다른 풀이를 찾아보니 백트래킹을 사용하여 더 빠른 속도를 낼 수 있음을 알게되었습니다.
- 어느경우에 백트래킹을 사용하면 좋은지 학습했습니다.
- dfs 문제가 조금 복잡해지면 구현을 혼자서 완성 못하는데 혹시 다른분들 학습을 어떤식으로 하시는지요
=> [정연재] 2주차 화요일 일일 문제풀이

src/eunseo/week1/Hotel_155651.java, src/eunseo/week1/Network_43162.java
- prefix sum, dfs, bfs
- **레벨**: 2
- **문제명**: 호텔 대실
- **문제 링크**: [호텔 대실](https://school.programmers.co.kr/learn/courses/30/lessons/155651?language=java)
- **레벨**: 3
- **문제명**: 네트워크
- **문제 링크**: [네트워크](https://school.programmers.co.kr/learn/courses/30/lessons/43162)
- 호텔 대실: 누적합에 대해서 알게 되었습니다.
- 네트워크: 이 문제를 보고 전혀 BFS/DFS의 문제라고 생각하지 못했습니다... 그래프 적인 문제가 나올 때는 BFS/DFS를 생각해보게 될 것 같습니다.
- 호텔 대실: 시작 시각으로 정렬한 다음에 Queue로 종료 시각 + 10분 에 해당하는 것을 Queue에서 제거하고 Room이 나온 개수를 세줬습니다. ( 이 접근 방법은 생각 했는 데, 개발을 어떻게 해야하는 지 고민하다가 결국에는 chatGPT의 힘을 빌렸습니다 )
- 네트워크: BFS/DFS를 아직 어떻게 다뤄야 할지 모르겠습니다ㅎㅎ.. 너무 어렵네요
=> [공은서] 1주차 실전문제풀이 

src/hyojin/backtracking/양궁대회.java, src/hyojin/simulation/다리를지나는트럭.java
- 백트래킹
- **레벨**: 2
- **문제명**: 양궁대회
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/92342?language=java
- 백트래킹을 복습하며 다시 공부할 수 있었습니다.
- 백트래킹은 가능한 모든 경우를 탐색하며, 유망하지 않은 경로는 조기에 차단하는 알고리즘 기법입니다.
- 탐색 중간에 조건이 맞지 않으면 이전 단계로 돌아가 다른 경로를 시도합니다.
- 해를 찾은 후 원복(backtrack)을 통해 이전 상태로 되돌려 탐색을 계속합니다.
- 백트래킹 반복문 흐름이 잘 이해가 안 돼서 추가 정리가 필요합니다. 
- 정답지 보고 풀었는데 다음과 같이 연속적 for문이 일어나 시간복잡도가 O(N^11)일 거 같은데 O(2^11)이라고 하네요,
백트래킹으로 유망함수 타고 내려가니  O(N^11)보다 적겠지만 왜 O(2^11)인지 설명해주실 분 계실까요? 🤯
=> [우효진] 2주차 화요일 일일 문제풀이

src/seyoung/_2412_2주차/양궁대회.java
- 백트래킹
- **레벨**: 2
- **문제명**: 양궁대회
- **문제 링크**: [양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342)
- **문제 풀이**: [d4c3ae1](https://github.com/algorithm-study-2408/coding-tests-study-2412/pull/16/commits/d4c3ae17b1de5badb9f2254f8c92b99876f33735)
- 백트래킹
- 탐색할 필요가 없는 상태를 제외하고 재귀적으로 문제를 해결하는 알고리즘
- 조건에 부합하지 않으면 이전 수행으로 돌아감.
- dfs, bfs 등 재귀로 풀어야 하는 문제를 간단한 것부터 개인적으로 많이 풀어봐야 할 것 같습니다...
=> [홍세영] 2주차 화요일 일일문제풀이

src/jaehoon/_02주차/Lv02_양궁대회.java
- 백트래킹
- **레벨**: 2
- **문제명**: 양궁대회
- **문제 링크**: [양궁대회](https://school.programmers.co.kr/learn/courses/30/lessons/92342?language=java)
처음 시도할때 풀지 못했어요.
dfs로 접근했는데, 정답을 보고 백트래킹을 공부하고 풀게 됐어요.
모든 경우를 탐색하면서 남은 화살 개수와 어피치의 과녁을 비교해서 얻을 수 있는 점수를 계산합니다.
재귀를 돌고 되돌아올때는 해당 과녁을 다시 복원하도록 합니다.
책에 있는 정답지를 보면서 풀었는데, 백트래킹도 익숙하지 않아서 여러 문제를 풀어보고 이 문제도 몇일내로 다시 풀어봐야할 것 같아요.
=> [이재훈] 2주차 화요일 일일 문제풀이

src/hyojin/hash/베스트앨범.java, src/hyojin/sql/분기별_분화된_대장균의_개체_수_구하기.sql
- 해시, 정렬
- **레벨**: 2
- **문제명**: 베스트앨범
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/42579
- 다중 정렬시 해시 정렬에 대해서 복습할 수 있었습니다.
- merge, computeIfAbsent에 대해서 다시 한번 공부할 수 있었습니다.
- 다른 분들 코드를 보니, `판매량이 동일할 때의 고유번호 낮은 순으로 정렬한다.` 제약은 안 보이는 거 같던데
어떻게 돌아가는지 궁금하군요..ㅎ
=> [우효진] 2주차 수요일 일일 문제풀이 

src/eunseo/week2/BestAlbum_42579.java
- 해시
- **레벨**: 3
- **문제명**: 베스트앨범
- **문제 링크**: [베스트앨범](https://school.programmers.co.kr/learn/courses/30/lessons/42579)
- `getOrDefault` : 찾는 키가 존재한다면 찾는 키의 값을 반환, 없다면 기본 값 반환
- `stream().mapInt().toArray()`: List에서 Array 변환
- 제 생각에는 코드들이 한눈에 안 들어오는 것 같은 데(아마도 함수의 함수를 넣어서 그런 건가 싶기도 합니다.), 더 간단하게 짤 수 있는 방법이 있을까요??
=> [공은서] 2주차 수요일 일일문제풀이

src/jaehoon/_02주차/Lv03_베스트앨범.java
- 해시
- **레벨**: [Lv03]
- **문제명**: [베스트 앨범]
- **문제 링크**: [베스트 앨범](https://school.programmers.co.kr/learn/courses/30/lessons/42579)
- 해시와 우선순위 큐를 이용해서 풀었는데, 상세한  요구사항들을 구현하는 부분이 부족하다고 느꼈어요.
- 예외 케이스를 항상 생각해서 풀어야 할 것 같네요.
- 우선순위 큐로 재생수가 많은 것 부터 뽑아내려고 했는데, 성능상 더 좋은 방법이 있을 것 같아요. 좋은 아이디어 있으면 알려주시면 감사합니다.
- 처음에 장르별 음악을 2개씩 뽑아내서 배열에 넣었었는데요. 1개만 있는 케이스들이 있는 것 같아요. 배열이라 0으로 초기화 되서 조금 헤맷네요.
=> [이재훈] 2주차 수요일 일일 문제풀이

src/hyojin/string/괄호변환.java
- 문자열
- **레벨**: 2
- **문제명**: 괄호변환
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/60058
- `빈 문자열에 첫 번째 문자로 '('를 붙입니다.` ==  새로운 문자열을 만들기 시작하는 단계를 의미
- `4-4. u의 첫 번째와 마지막 문자를 제거하고, 나머지 문자열의 괄호 방향을 뒤집어서 뒤에 붙입니다.`는 균형잡힌 문자열이지만 올바르지 않음으로 제시한 방향으로 알고리즘 수행하면 올바른 문자가 된다 (?)
- 왜 이런 과정을 수행하면 정답이 되는가?
- solution(v)는 재귀 호출을 통해 항상 "올바른 괄호 문자열"로 변환됩니다.
- ("(" + solution(v) + ")" + reverse(...)) 구조는 항상 "올바른 괄호 문자열"의 형태입니다.
- reverse 함수가 u의 잘못된 부분을 올바르게 변환합니다.
- u의 잘못된 부분(첫 번째와 마지막 문자)을 제거하고 나머지 괄호를 뒤집으면 균형이 맞는 "올바른 괄호 문자열"로 변환됩니다.
- 문제를 파악해나가는 과정이 다소 복잡하게 느껴졌습니다. 다른 분들은 어떻게 접근하셨나요?
=> [우효진] 2주차 금요일 일일문제풀이

src/jaehoon/_02주차/Lv02_괄호변환.java
- 문자열, 재귀
- **레벨**: 2
- **문제명**: 괄호변환
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/60058
- subString(startIndex, endIndex); `endIndex는 포함하지 않음`
- 분할정복 (Divide and Conquer) `분할 정복법은 재귀적으로 자신을 호출하면서 그 연산의 단위를 조금씩 줄어가는 방식`
- 문제를 이해하는데 시간이 많이 걸리고 헤맸네요. `문자열 w를 두 "균형잡힌 괄호 문자열" u, v로 분리합니다` 가 무슨말인지 이해하는데 한참 걸렸어요. 그리고  `1단계부터 다시 시작한다라는 말도요.` 문제를 이해하는게 어렵네요.
- 지문이 긴 문제는 다들 어떻게 이해하면서 접근하시는지 궁금해요
=> [이재훈] 2주차 금요일 일일문제풀이

src/yeonjae/괄호변환.java
- 문자열
- **레벨**: 2
- **문제명**: 괄호변환
- **문제 링크**: (https://school.programmers.co.kr/learn/courses/30/lessons/60058)
- 이번에는 조건에 따라 구현만하면 되는 문제같아서 비교적 쉬웠던거 같습니다.
- 그래도 생각한걸 코드로 푸는 노력을 더 해야겠다는 생각을 했습니다.
- 변수명 정하기 이번에 특히 어려웠던거 같습니당..ㅎㅎ
- 이런 문제는 단순 구현문제일까요?
- 코테풀때마다 각 문제 당 점수가 있는데 해당 문제같은경우에는 몇점정도 되는 문제일까요?
=> [정연재] 2주차 금요일 일일문제풀이

src/hyojin/bfs/거리두기확인하기.java, src/hyojin/test/K진수에서_소수점_구하기_오답.java, src/hyojin/test/K진수에서_소수점_구하기_정답.java, src/hyojin/test/삼각달팽이.java
- [주제 입력]
- **레벨**: 2
- **문제명**:
- k진수에서 소수점 구하기
- 거리두기 확인하기 
- **문제 링크**: 
- https://school.programmers.co.kr/learn/courses/30/lessons/92335
- https://school.programmers.co.kr/learn/courses/30/lessons/81302
- k진수에서 소수점 구하기
- 문제 접근 방식 공부
-  거리두기 확인하기
- 멘헤튼 거리 계산 방식 이해
- bfs 활용 복습  
- 라이브로 진행!
- k진수 소수점 구하기 문제는 어떤 알고리즘일까요? 문자열?
=> [우효진] 2주차 실전문제풀이

.idea/uiDesigner.xml, src/jonghun/week03/삼각달팽이.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 삼각달팽이
- **문제 링크**: [문제 링크](https://school.programmers.co.kr/learn/courses/30/lessons/68645)
- 아이패드로 그림그려가면서 푸니까 조금 접근이 쉬워졌다는 점
- 
- 서커스 계속 하다가 결국 답지를 참고했습니다.. 다른 분들은 어떻게 접근하셨는지 궁금합니다
=> [주종훈] 3주차 월요일 일일문제풀이

src/jaehoon/_03주차/Lv02_삼각달팽이.java
- 구현?
- **레벨**: Lv02
- **문제명**: 삼각달팽이
- **문제 링크**: [삼각달팽이](https://school.programmers.co.kr/learn/courses/30/lessons/68645)
- 생각을 많이 하게 되는 문제인 것 같아요. 특별한 알고리즘으로 푸는거라기보단 패턴을 찾아내는게 중요하네요
- 일단 삼각형을 왼쪽으로 다 밀고, 이동하는 경로를 그림을 그려가면서 몇번 이동하는지 적어가면서 풀려고 했어요.
- 저는 반복을 몇번 돌아야 하는지 찾는게 어려웠어요. 처음에는 지점 포인터 변수를 만들어서 while문으로 돌리면서 지점포인터를 변화시키면서 풀려고 했는데, 조건이 엄청 복잡해지더라구요.
- 아래, 오른쪽, 위/왼쪽 방향으로 이동하는 3개의 패턴이 반복되는데, 몇번 반복할지를 계속 헷갈렸는데 다들 어떻게 접근하셨는지 궁금해요
=> [이재훈] 3주차 월요일 일일문제풀이

src/hyojin/simulation/삼각달팽이.java, src/hyojin/test/삼각달팽이.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 삼각 달팽이 
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/68645
- 이전에 비슷한 문제를 풀어봐서 top, left, right, bottom 값을 이용해서 풀어보려다가 실패하고, 지부장님 도움을 받아 문제 규칙에 맞춰 값을 변경하고 구현하는 방법을 다시 공부했습니다.
- 커밋을 잘못 해서, 로직은 이 링크에서 확인해주세요 😂
- https://github.com/algorithm-study-2408/coding-tests-study-2412/blob/3fbd17134135a53d1454d26e97da1f4c3bc8642a/src/hyojin/test/%EC%82%BC%EA%B0%81%EB%8B%AC%ED%8C%BD%EC%9D%B4.java 
- 다른 분들도 비슷하게 푼 거 같아서 패스!
=> [우효진] 3주차 월요일 일일문제풀이

src/hyojin/simulation/_1차캐시.java
- 큐
- **레벨**: 2
- **문제명**: 1차캐시
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/17680
- LRU를 활용하여 문제 접근 방법
- 오늘 회사이슈로 늦어서, 리뷰 포인트는 추후 정리하겠습니다!!
=> [우효진] 2주차 화요일 일일문제풀이

src/yeonjae/simulation/삼각달팽이.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 삼각 달팽이
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/68645
- 그림이 주어졌어도 이차배열로 풀어내는방법
- 패턴을 찾는 방법 (많이 풀어봐야할거같습니다...)
- 도저히 패턴을 찾기가 어려워서 답지 참고했는데 다른풀이방법이 있으실까요
- 그리고 다른분들한테 난이도가 어땠는지도 궁금합니다! 같은 레벨 2라고해도 문제마다 난이도 차이가 있는거 같네용 ㅠㅠ
=> [정연재] 3주차 월요일 일일문제풀이

src/seyoung/_2412_3주차/캐시.java
- LRU
- **레벨**: 2
- **문제명**: 캐시
- **문제 링크**: [캐시](https://school.programmers.co.kr/learn/courses/30/lessons/17680)
- LRU 알고리즘... 아직 좀 헷갈림
- LRU 개념이 낯설어서 문제 자체를 이해하는데 오래 걸렸습니다 ㅜㅜ
=> [홍세영] 3주차 화요일 일일문제풀이

src/jaehoon/_02주차/live/Lv02_k진수에서_소수점_구하기.java, src/jaehoon/_03주차/Lv02_타겟넘버.java
- 재귀, 분할정복
레벨: 2
문제 링크: [타겟넘버](https://school.programmers.co.kr/learn/courses/30/lessons/43165?language=java)
- 큰 문제를 어떻게 작은 문제로 쪼갤까를 생각하게 된 것 같아요.
- 예전에 풀었었는데, 다시 풀었을때도 똑같은 접근으로 하게 되네요.
- k진수에서_소수점_구하기는 라이브때 푼 문제올리거라 무시하고 봐주세요.
- 더 효율적인 방법이 있을까요?
=> [이재훈] 3주차 수요일 일일 문제풀이

src/hyojin/bfs/타겟넘버.java, src/hyojin/simulation/_1차캐시.java, src/hyojin/test/예상대진표.java
- bfs
- **레벨**: 2
- **문제명**: 타겟넘버
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/43165
- 처음에는 for문으로 처리를 해야하나 고민했습니다.
- 이전에 풀어봤던 문제여서 복습할 수 있었습니다.
- bfs, dfs 쉽게 파악하기 팁이 있을까요 😂
=> [우효진] 2주차 수요일 일일문제풀이

src/jaehoon/_02주차/live/Lv02_거리두기_확인하기.java, src/jaehoon/_02주차/live/Lv02_거리두기_확인하기_BFS.java, src/jaehoon/_03주차/Lv02_예상대진표.java
- 시뮬레이션?
- **레벨**: Lv02
- **문제 링크**: [예상대진표](https://school.programmers.co.kr/learn/courses/30/lessons/12985)
- 처음에는 트리를 만들어서 풀어야 되나라고 고민했는데, 단순한 계산만으로 풀 수 있네요.
- 라운드를 올라갈때마다 배정되는 번호가 홀수일수도 있고 짝수일수도 있어서 (X+1) / 2 해주어서 번호를 초기화 시켜줍니다.
- **거리두기 확인하기 문제는 라이브때 진행했던 문제라서 무시해주세요.**
- 이건 무슨 분류가 어떻게 될까요?
=> [이재훈] 3주차 목요일 일일문제풀이 

src/seyoung/_2412_3주차/타겟넘버.java
- dfs
- **레벨**: 2
- **문제명**: 타켓 넘버
- **문제 링크**: [타겟 넘버](https://school.programmers.co.kr/learn/courses/30/lessons/43165)
- dfs 되짚기
- 재귀와 재귀를 합산해서 연산하는 방식
- dfs를 사용해야 하는 문제를 바로 파악하는게 아직 어려운 것 같습니다
=> [홍세영] 3주차 수요일 일일문제풀이

src/jaehoon/_03주차/live/Lv02_주차요금계산.java, src/jaehoon/_03주차/live/Lv02_피로도.java, src/jaehoon/_04주차/Lv02_방문길이.java
- DFS, 구현
- **레벨**: Lv02
- **문제**: [피로도](https://school.programmers.co.kr/learn/courses/30/lessons/87946)
- **레벨**: Lv02
- **문제**: [주차요금계산](https://school.programmers.co.kr/learn/courses/30/lessons/92341)
**주차요금계산**
- map의 활용도를 좀더 배운것 (`computeIfAbsent`, `putIfAbsent`, `Map.Entry<key, value>`)
- computeIfAbsent : 있으면 맵 반환, 없으면 새로 만들어서 저장하고 value를 반환
- putIfAbsent : 있으면 맵 반환, 없으면 새로 만들어서 저장하고 null 반환
- 굳이 스택을 만들지 않아도 될 것 (입 출차가 확실한 Map만 사용해도 풀수 있을 것
주차요금계산은 1점밖에 안주네요 ㅎㅎ 다들 어떤식으로 푸시는지 궁금합니다.
=> [이재훈] 3주차 실전문제풀이 DFS, 구현

src/hyojin/bfs/피로도.java, src/hyojin/dfs/피로도.java, src/hyojin/simulation/예상대진표.java, src/hyojin/simulation/주차요금계산.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 예상대진표
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/12985
- 이전에 풀었던 문제인데 복습할 수 있었습니다!
- 다른 분들 풀이가 더 깔끔해서 참고가 되었어요
=> [우효진] 목요일 일일문제풀이

src/yeonjae/simulation/방문길이.java
- 시뮬레이션, 경로 탐색
- **레벨**: 2
- **문제명**: 방문길이
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/49994
- 양방향(중복처리) 하는방법에 대해 고민을 많이 해보았습니다.
- 이 문제 알고리즘 유형이 작성한게 맞는지 궁금합니다
- 그리고 다른분들은 중복처리를 어떻게 했는지도 궁금하네용
=> [정연재] 4주차 월요일 일일 문제풀이

src/jaehoon/_04주차/Lv02_더_맵게.java, src/jaehoon/_04주차/Lv02_방문_길이.java, src/jaehoon/_04주차/Lv02_점프와_순간이동.java, src/jaehoon/_04주차/Lv02_카펫.java
- 구현
- **레벨**: Lv02
- **문제링크**: [방문길이](https://school.programmers.co.kr/learn/courses/30/lessons/49994)
- 이전 dfs에서 좌표를 이동할때는 정점을 방문했는지 안했는지만 확인했다면, 이번문제는 간선(이동 경로)을 체크하는 문제였네요.
- 양쪽으로 이동하는 경우가 있기 때문에 A->B, B->A 경로를 모두 저장해야한다는 것을 생각해야하네요. 재밌는 문제였어요.
- 이전 PR을 merge안한 상태로 다시 올려서 조금 겹쳤네요.
- 이름 바꾸고 다시 올립니다.
=> [이재훈] 4주차 월, 화요일 일일 문제풀이

src/hyojin/simulation/방문길이.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 방문길이
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/49994?language=java
- 처음에는 이동 좌표를 만들어서 풀어야하는 것 같았는데, set을 이용하여 풀 수 있다는 점을 배웠습니다.
- 다른 분들은 어떻게 풀이하셨는지 궁금해요!!
=> [우효진] 4주차 월요일 일일 문제풀이

src/hyojin/test/더맵게.java, src/hyojin/test/이모티콘할인행사.java
- 기타
- **레벨**: 2
- **문제명**: 더맵게, 이모티콘 할인행사
- **문제 링크**: 
- https://school.programmers.co.kr/learn/courses/30/lessons/42626
- https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 어제 오늘 너무 바빠서 새벽에 복습하고 다시 정리하겠습니다!!!
-
=> [우효진] 4주차 화요일, 수요일 일일 문제풀이

src/yeonjae/queue/더맵게.java
- 힙
- **레벨**: 2
- **문제명**: 더 맵게
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/42626
- 우선순위 큐를 쓰니 비교적 쉽게 푼거같습니다.
- 우선순위 큐 안쓰는 방법도 궁금하네용
=> [정연재] 4주차 화요일 일일 문제풀이

src/jaehoon/_04주차/live/Lv02_과제_진행하기.java, src/jaehoon/_04주차/live/Lv02_행렬_테두리_회전하기.java, src/jaehoon/_04주차/순열_조합/순열.java, src/jaehoon/_04주차/순열_조합/조합_재귀.java, src/jaehoon/_04주차/순열_조합/조합_중첩for문.java
- [주제 입력]
- **레벨**: Lv02
- **문제 링크**: [과제_진행하기](https://school.programmers.co.kr/learn/courses/30/lessons/176962)
- **레벨**: Lv02
- **문제 링크**: [행렬_테두리_회전하기](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
- 리스트를 정렬하는 Comparator.comparingInt에 대해서 한번더 확인
- 배열을 회전할때 배열의 인덱스를 다루는 방법
=> [이재훈] 4주차 실전문제풀이 [Lv02_과제_진행하기, Lv02_행렬_테두리_회전하기]

src/seyoung/_2412_4주차/과제진행하기.java, src/seyoung/_2412_4주차/행렬테두리회전하기.java
- 큐, 시뮬레이션
- **레벨**: 2
- **문제명**: 과제 진행하기
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/176962](https://school.programmers.co.kr/learn/courses/30/lessons/176962)
- **레벨**: 2
- **문제명**: 행렬 테두리 회전하기
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/77485](https://school.programmers.co.kr/learn/courses/30/lessons/77485)
- 두 문제 다 while 문 안쪽 조건에서 gpt 도움을 받았습니다 ㅎㅎ.. 아직 시간 내에 구체적인 조건을 짜는 게 힘든 것 같아요
=> [홍세영] 4주차 주말 일일 문제 풀이 [과제 진행하기 / 행렬 테두리 회전하기]

src/hyojin/binarysearch/퍼즐게임챌린지.java
- 이진 탐색
- **레벨**: 2
- **문제명**: 퍼즐게임챌린지
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/340212
- 시간복잡도를 고려해서 알고리즘 파악하기
- 이진탐색 복습
=> [우효진] 4주차 목요일 일일 문제풀이

src/yeonjae/퍼즐게임챌린지.java
- 이진탐색
- **레벨**: 2
- **문제명**: 퍼즐 게임 챌린지
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/340212
- 수식 알아내서 코드로 풀어낼려고했는데.. 도저히 안풀려서 답지봤습니당ㅎㅎ 말로 꼬은 문제 많이 풀어봐야겠어요
=> [정연재] 4주차 목요일 일일 문제풀이

src/seyoung/_2412_5주차/요격시스템.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 요격 시스템
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/181188](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
- 요격미사일이 어느 순간 최소가 될지 고민해보면 생각보다 문제가 간단한 코드로 풀림...
=> [홍세영] 5주차 월요일 일일문제풀이

src/jaehoon/_05주차/Lv02_요격시스템.java, src/jaehoon/_05주차/Lv02_이모티콘_할인행사.java, src/jaehoon/_05주차/Lv02_이모티콘_할인행사_리팩토링.java
- 시뮬레이션, 완전탐색
- **레벨**: 2
- **문제명**: [요격시스템](https://school.programmers.co.kr/learn/courses/30/lessons/181188)
- **레벨**: 2
- **문제명**: [이모티콘 할인행사](https://school.programmers.co.kr/learn/courses/30/lessons/150368)
- 여러개를 한번에 처리할때는 정렬을 하고 지점을 이동해가면서 풀어야함, 개구간(시작점과 끝점을 포함하지 않는 구간)
- 이모티콘 할인행사 문제에서 여러개의 조합의 경우를 처리할때는 완전탐색을 해야된다는 것을 알게됐습니다. DFS를 이용할 수 있음
- 레벨2인 이모티콘 할인행사 문제가 되게 어렵더라구요. 난이도를 어떻게 느끼셨을까요?
- 문제를 풀지 못했을때 어떤식으로 정답을 확인하고 연습하시는지도 궁금해요
=> [이재훈] 5주차 월요일, 화요일 일일문제풀이

src/hyojin/simulation/요격시스템.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 요격시스템
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/181188
- 미사일의 끝점을 기준으로 정렬시켜 해당 미사일이 커버가능한 시작점을 찾는 원리
- 개구간: 수학에서 구간을 표현할 때, 시작점과 끝점을 포함하지 않는 구간
- gpt에서는 개구간을 표현하기 위해 아래처럼 구현하더라구요, 비슷하게 고려하신 분 계실까요?
```
if (lastIntercept < start) {
interceptors++;
lastIntercept = end - 0.5;
}
```
=> [우효진] 5주차 월요일 일일 문제풀이

src/yeonjae/bfs/무인도여행.java, src/yeonjae/simulation/과제진행하기.java, src/yeonjae/행렬테두리회전하기.java, src/yeonjae/행렬테두리회전하기_재훈.java
- dfs
- **레벨**: 2
- **문제명**: 무인도 여행
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/154540
- bfs 복습했습니다.
- 주말 문제도 포함되어있으니 무인도 여행만 봐주시면 될거같습니다.
- 월, 화 문제도 천천히 커밋하겠습니다.
=> [정연재] 5주차 수요일 일일 문제풀이

src/jaehoon/_00연습/순열_조합/순열.java, src/jaehoon/_00연습/순열_조합/조합_재귀.java, src/jaehoon/_00연습/순열_조합/조합_중첩for문.java, src/jaehoon/_00연습/스택/BOJ_17298_오큰수.java, src/jaehoon/_00연습/스택/Lv02_올바른괄호.java, src/jaehoon/_00연습/스택/Lv02_주식가격.java, src/jaehoon/_05주차/Lv02_무인도_여행_BFS.java, src/jaehoon/_05주차/Lv02_무인도_여행_DFS.java, src/jaehoon/_05주차/Lv02_요격시스템.java
- dfs, bfs
- **레벨**: Lv02
- **문제명**: 무인도 여행
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/154540
- dfs, bfs를 복습했네요. 탐색시 리턴값으로 값을 누적해줘야하는 경우에 대해서 풀게됐어요.
- 처음에 dfs로 풀었는데, 리턴값을 이상하게 처리해서 좀 헤맸네요... 꾸준히 풀어봐야할 것 같아요.
- 다른거 연습하다가 PR을 같이 올렸는데요. 무인도여행 문제만 봐주시면 감사합니다.
- 이걸로 봐주세요.!! https://github.com/algorithm-study-2408/coding-tests-study-2412/commit/c911cbe8b05f2ca43fd625ef1051a68309d288d9
=> [이재훈] 5주차 수요일 일일 문제풀이

src/seyoung/_2412_5주차/무인도여행.java, src/seyoung/_2412_5주차/조이스틱.java
- bfs, 그리디
- **레벨**: 2
- **문제명**: 무인도 여행
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/154540](https://school.programmers.co.kr/learn/courses/30/lessons/154540)
- **레벨**: 2
- **문제명**: 조이스틱
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/42860](https://school.programmers.co.kr/learn/courses/30/lessons/42860)
- bfs가 오랜만이라 복습하는 시간을 가졌습니다
- 조이스틱은 계산이 자꾸 틀려서 애먹다 답지 봤습니다...
=> [홍세영] 5주차 수목 일일문제풀이

src/seyoung/_2412_5주차/마법의엘레베이터.java
- DP
- **레벨**: 2
- **문제명**: 마법의 엘리베이터
- **문제 링크**: [https://school.programmers.co.kr/learn/courses/30/lessons/148653](https://school.programmers.co.kr/learn/courses/30/lessons/148653)
- 문제 유형을 파악하는 팁이 있으신가요?
=> [홍세영] 5주차 금요일 일일 문제풀이

src/hyojin/simulation/조이스틱.java
- 시뮬레이션
- **레벨**: 2
- **문제명**: 조이스틱
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/42860
- 이전에 몇 번 풀었지만 어렵네요!!
- 순서대로 가는 것과, 뒤로 돌아가는 것 중 이동수가 적은 것을 선택
- 처음부터 뒷부분을 먼저 입력하는 것이 더 빠른 경우까지 고려해야하는 점
=> [우효진] 5주차 목요일 일일 문제풀이

src/hyojin/greedy/지뢰찾기.java
- 그리디
- **레벨**: 골드 4
- **문제명**: 지뢰찾기
- **문제 링크**:  https://www.acmicpc.net/problem/9082
- 배열을 이용한 상태 추적
- 지뢰 갯수 찾기 공식이 존재한다.
```
지뢰 경우의 수 총합에서 0번째, n-1번째가 각각 0이 아니라면 1씩 더 한후, 3으로 나눈 몫이 지뢰 개수를 구할 수 있다.
ex)
1 2 3 3 2 1 인경우
12 + (처음 1 + 끝 1) = 14
14 // 3 = 4
```
- 처음에 이해가 안 갔었는데, 다시 보니까 블록을 기준으로 자신, 좌, 우 모두 0이 아니라면 -1해서 카운팅하는 로직인 거 같아요 이게 맞을까요?
=> [우효진] 6주차 월요일 일일 문제풀이

src/yeonjae/greedy/마법의엘레베이터.java, src/yeonjae/greedy/조이스틱.java
- 그리디 (목)
- 그리디, dp (금)
- **레벨**: 2
- **문제명**: 조이스틱
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/42860
- **레벨**: 2
- **문제명**: 마법의 엘레베이터
- **문제 링크**: https://school.programmers.co.kr/learn/courses/30/lessons/148653
- 오랜만에 그리디 문제 풀어서 재밌었네요 복습하고 갑니다.
- 마법의 엘레베이터에서 조건이 5인 경우를 어떻게 해야할지 감이 안와서 답지 봤습니당.
- 문제 유형에 그리디라는게 없었어도 풀었을지가 의문이네요 혹시 그리디 문제 판별하는 기준들이 있으실까요
=> [정연재] 5주차 목요일 금요일 일일 문제풀이

src/jaehoon/_06주차/BOJ_9082_지뢰찾기.java, src/jaehoon/_06주차/BOJ_9082_지뢰찾기2.java
- 그리디
- **레벨**: 골드4
- **문제명**: [지뢰찾기](https://www.acmicpc.net/problem/9082)
- 그리디에 대한 개념을 다시 공부하게 됐어요. 아직 잘 이해가 가지는 않지만 연습해봐야겠어요.
- 문제를 풀지못해서 다른 분들 푼 것을 보고 정리했네요.
- 백준이라서 입력, 출력 코드때문에 조금 지저분해졌네요.
- 그리디는 명제를 만들어서 접근해야한다고 해요.
- "중복을 포함한 모든 최대 지뢰의 총합을 3으로 나누면 최대값이 나온다"라는 명제가 나오는데, 다들 어떤식으로 접근하셨나요?
=> [이재훈] 6주차 월요일 일일 문제풀이

src/jaehoon/_06주차/BOJ_1461_도서관.java, src/jaehoon/_06주차/BOJ_1461_도서관_우선순위큐.java
- 그리디
- **레벨**: 골드4
- **문제명**: [도서관](https://www.acmicpc.net/problem/1461)
- 이번에 그리디에 대해서 공부하게 되었는데, 접근하는 꿀팁이 있더라구요.
- 작은 단계마다 최적의 선택을 해서 마지막에도 최적의 선택이 되게 하는 것들에 그리디를 적용할 수 있는데요.
- `그리디로 풀꺼면 -> 명제를 생각하고, 정렬 또는 우선순위큐로 풀 수 있는지 확인해서 푼다` 였어요.
- 거의 정렬에서 풀리는 것 같은데, 어떤 문제를 그리디로 풀어야하는지, 그리디로 접근할 때 어떤식으로 푸시나요?
- 정렬과 우선순위큐를 이용한 풀이를 각각 올렸어요.
=> [이재훈] 6주차 화요일 일일문제풀이

src/seyoung/_2501_6주차/도서관.java
- 그리디
- **레벨**: 골드4
- **문제명**: 도서관
- **문제 링크**: [https://www.acmicpc.net/problem/1461](https://www.acmicpc.net/problem/1461)
- 그리디는 다양한 접근 방법이 있어서 찾아가며 공부하기 좋은 것 같습니다
=> [홍세영] 6주차 화요일 일일문제풀이

src/jaehoon/_06주차/BOJ_13458_시험감독.java, src/jaehoon/_06주차/BOJ_3109_빵집.java
- 그리디
- **문제명**: 
- [빵집](https://www.acmicpc.net/problem/3109)
- [시험감독](https://www.acmicpc.net/problem/13458)
- boolean을 리턴해서 더이상 재귀가 타지 않게 하는 방법
- 시험장 수 (N), 응시자 수 (i) 모두 100만이어서 1조가 나올 수 있기 때문에, count를 long으로 변환해줘야함
- 올림 계산하는 테크닉을 알게됨
=> [이재훈] 6주차 수, 목요일 일일문제풀이

src/hyojin/greedy/BOJ_1541_잃어버린괄호.java, src/hyojin/greedy/BOJ_1931_회의실배정.java, src/hyojin/greedy/도서관.java, src/hyojin/greedy/빵집.java
- 그리디
- **문제명**: 
- 도서관
- 빵집
- **문제 링크**: 
- https://www.acmicpc.net/problem/1461
- https://www.acmicpc.net/problem/3109
- 접근 순서를 오른쪽 위, 오른쪽, 오른쪽 아래로 풀어야한다는 점
- 경로 재탐색하지 않기
=> [우효진] 6주차 수요일 일일문제풀이

src/hyojin/simulation/BOJ_20546_기적의매매법.java
- 시뮬레이션
- **레벨**: 실버 5
- **문제명**: 기적의 매매법
- **문제 링크**: https://www.acmicpc.net/problem/20546
- 시뮬레이션 공부!
=> [우효진] 7주차 월요일 일일문제풀이

src/jaehoon/_07주차/BOJ_20546_기적의_매매법.java
- 시뮬레이션
- **레벨**:  실버 5
- **문제명**: [기적의 매매법](https://www.acmicpc.net/problem/20546)
- 구현 문제를 많이 풀어보지 못한게 드러나네요. 문제 자체는 쉬웠는데, 실버 5인데도 구현하는데 시간이 쫌 걸리네요
- 기업코테는 구현문제가 자주 나오니 많이 풀어봐서 익숙해져야 할 것 같아요.
- 구현문제는 메서드명이나 변수명을 신경쓰게돼요. 이게 더 문제 풀이 시간을 더 오래걸리게 만드네요.
=> [이재훈] 7주차 월요일 일일문제풀이 - 기적의 매매법

src/hyojin/simulation/BOJ_10809_기상캐스터.java
- 구현
- **레벨**: 실버5
- **문제명**: 기상캐스터
- **문제 링크**: https://www.acmicpc.net/problem/10709
- 문제 규칙을 이해하면 반복문으로 해결할 수 있었습니다.
=> [우효진] 8주차 월요일 일일문제풀이

src/jaehoon/_08주차/BOJ_10709_기상캐스터.java, src/jaehoon/_08주차/BOJ_20546_기적의_매매법.java
- [주제 입력]
- **레벨**: 실버5
- **문제명**: [기상캐스터](https://www.acmicpc.net/problem/10709)
- **레벨**: 실버5
- **문제명**: [기적의매매법](https://www.acmicpc.net/problem/20546)
- 구현은 난이도가 낮아도 시간이 오래걸리네요.
- 기업에서 출제되는 문제들이 구현 문제가 많으니 많이 풀어봐야 할 것 같아요.
- 기적의매매법은 전에 풀어본 적이 있어서, 객체지향으로 풀어봤어요. (원래 이렇게 풀면 시간이 너무 오래걸릴 수 있을 것 같네요.)
=> [이재훈 ]8주차 월, 화요일 일일문제풀이

src/jaehoon/_08주차/BOJ_11559_PuyoPuyo.java
- 구현
- **레벨**: 골드4
- **문제명**: Puyo Puyo
- **문제 링크**: https://www.acmicpc.net/problem/11559
- 중력을 다루는 구현을 어떻게 해야할까를 고민하게 되었고, 이부분의 구현을 논리적으로 생각하는 방법을 연습하게 된 것 같아요.
- DFS, BFS중 어떤게 더 사용하기 편하고, 효율적이신가요?
- 중력 적용하는 가장 효과적인 방법이 뭘까요?
=> [이재훈] 8주차 실전문제풀이

src/jaehoon/_09주차/BOJ_20125_쿠키의_신체_측정.java, src/jaehoon/_09주차/BOJ_3085_사탕게임.java
- 구현
- 실버2
- 사탕게임
- https://www.acmicpc.net/problem/3085
- 실버4
- 쿠키의 신체측정
- https://www.acmicpc.net/problem/20125
- 구현문제는 쉬우면서도 어렵네요. 
- 사탕게임에서 전치행렬에 대해 배웠어요.
- 효과적인 접근 방법이 궁금하네요.
=> [이재훈] 9주차 1, 2번 문제풀이

src/jaehoon/_09주차/live/BOJ_14500_테트로미노.java, src/jaehoon/_10주차/BOJ_2468_안전영역.java, src/jaehoon/_10주차/BOJ_2606_바이러스.java, src/jaehoon/_10주차/BOJ_7576_토마토.java
- 그래프
- **레벨**: 실버 3
- **문제명**: 바이러스
- **문제 링크**: https://www.acmicpc.net/problem/2606
- **레벨**: 실버 1
- **문제명**: 안전영역
- **문제 링크**: https://www.acmicpc.net/problem/2468
- **레벨**: 골드 5
- **문제명**: 토마토
- **문제 링크**: https://www.acmicpc.net/problem/7576
- bfs시에 방문배열을 정수형으로 둬서 퍼져나가는 시간을 증가시키면서 저장하는 방법을 배움
=> [이재훈] 10주차 일일문제풀이

src/seyoung/_2502_7주차/기적의_매매법.java
- 시뮬레이션
- **레벨**: 실버 5
- **문제명**: 기적의 매매법
- **문제 링크**: [기적의 매매](https://www.acmicpc.net/problem/20546)
- 틀렸는데 일단 올리고 내일 재시도 하겠습니다 ㅜㅜ 다른 분들 풀이도 궁금하네
=> [홍세영] 8주차 화요일 일일문제풀이
